### ISSUE TITLE
react-native-animatable - bundling failed

### ISSUE THREAD

**Issue by Noitidart** [tuantle/react-native-search-header#16]
Hi there,

After installing I get this error:

```
error: bundling failed: UnableToResolveError: Unable to resolve module `react-native-animatable` from `C:\Users\Mercurius\Documents\GitHub\trustedplatform_android\node_modules\react-native-search-header\search-header.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at ModuleResolver.resolveNodeDependency (C:\Users\Mercurius\Documents\GitHub\trustedplatform_android\node_modules\metro-bundler\src\node-haste\DependencyGraph\ModuleResolution.js:292:11)
    at ResolutionRequest.resolveDependency (C:\Users\Mercurius\Documents\GitHub\trustedplatform_android\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:109:14)
    at dependencyNames.map.name (C:\Users\Mercurius\Documents\GitHub\trustedplatform_android\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:134:10)
    at Array.map (<anonymous>)
    at ResolutionRequest.resolveModuleDependencies (C:\Users\Mercurius\Documents\GitHub\trustedplatform_android\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:133:42)
    at Promise.resolve.then (C:\Users\Mercurius\Documents\GitHub\trustedplatform_android\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:173:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Do you have any ideas on how I can fix? Thanks for this awesome module by the way!

**Comment by Noitidart** [comment]
I installed it manually, things work now! Wow that was weird.
